---
- hosts: all
  become: true
  tasks:

  - name: Install Docker
    yum:
      name: docker
      state: present
    tags:
      - docker

  - name: Add the ec2-user to the docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
    tags:
      - docker

  - name: Start the Docker service
    service:
      name: docker
      state: started
      enabled: yes
    tags:
      - docker

  - name: Install pip
    yum:
      name: python3-pip
      state: present
    tags:
      - pip
  - name: Install nginx
    yum:
      name: nginx
      state: present
      
  # Install & Configure Nginx
  - name: Start and enable Nginx
    service:
      name: nginx
      state: started
      enabled: true
  - name: Create sites-enabled directory
    file:
      path: /etc/nginx/sites-enabled
      state: directory
  - name: Create site configuration
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/site.conf
      owner: root
      group: root
      mode: 0644
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted

  - name: Install docker-compose
    pip:
      name: docker-compose
      state: present
    tags:
      - docker-compose

  - name: Create a directory for Kong
    file:
      path: /opt/kong
      state: directory
    tags:
      - kong

  - name: Create a docker-compose file for Kong
    copy:
      src: docker-compose.yml
      dest: /opt/kong/docker-compose.yml
    tags:
      - kong

  - name: Run Kong using docker-compose
    command: /usr/local/bin/docker-compose -f /opt/kong/docker-compose.yml up -d
    args:
      chdir: /opt/kong
    tags:
      - kong
